# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.25

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /snap/cmake/1210/bin/cmake

# The command to remove a file.
RM = /snap/cmake/1210/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/diht404/CLionProjects/language/processor

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/diht404/CLionProjects/language/processor

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/snap/cmake/1210/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/snap/cmake/1210/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/diht404/CLionProjects/language/processor/CMakeFiles /home/diht404/CLionProjects/language/processor//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/diht404/CLionProjects/language/processor/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named stack

# Build rule for target.
stack: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 stack
.PHONY : stack

# fast build rule for target.
stack/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stack.dir/build.make CMakeFiles/stack.dir/build
.PHONY : stack/fast

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/build
.PHONY : main/fast

#=============================================================================
# Target rules for targets named assembler_run

# Build rule for target.
assembler_run: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 assembler_run
.PHONY : assembler_run

# fast build rule for target.
assembler_run/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/assembler_run.dir/build.make CMakeFiles/assembler_run.dir/build
.PHONY : assembler_run/fast

#=============================================================================
# Target rules for targets named disassembler_run

# Build rule for target.
disassembler_run: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 disassembler_run
.PHONY : disassembler_run

# fast build rule for target.
disassembler_run/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/disassembler_run.dir/build.make CMakeFiles/disassembler_run.dir/build
.PHONY : disassembler_run/fast

#=============================================================================
# Target rules for targets named cpu_run

# Build rule for target.
cpu_run: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cpu_run
.PHONY : cpu_run

# fast build rule for target.
cpu_run/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpu_run.dir/build.make CMakeFiles/cpu_run.dir/build
.PHONY : cpu_run/fast

#=============================================================================
# Target rules for targets named sfml_test

# Build rule for target.
sfml_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sfml_test
.PHONY : sfml_test

# fast build rule for target.
sfml_test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sfml_test.dir/build.make CMakeFiles/sfml_test.dir/build
.PHONY : sfml_test/fast

assembler/assembler.o: assembler/assembler.cpp.o
.PHONY : assembler/assembler.o

# target to build an object file
assembler/assembler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/assembler_run.dir/build.make CMakeFiles/assembler_run.dir/assembler/assembler.cpp.o
.PHONY : assembler/assembler.cpp.o

assembler/assembler.i: assembler/assembler.cpp.i
.PHONY : assembler/assembler.i

# target to preprocess a source file
assembler/assembler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/assembler_run.dir/build.make CMakeFiles/assembler_run.dir/assembler/assembler.cpp.i
.PHONY : assembler/assembler.cpp.i

assembler/assembler.s: assembler/assembler.cpp.s
.PHONY : assembler/assembler.s

# target to generate assembly for a file
assembler/assembler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/assembler_run.dir/build.make CMakeFiles/assembler_run.dir/assembler/assembler.cpp.s
.PHONY : assembler/assembler.cpp.s

assembler/main.o: assembler/main.cpp.o
.PHONY : assembler/main.o

# target to build an object file
assembler/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/assembler_run.dir/build.make CMakeFiles/assembler_run.dir/assembler/main.cpp.o
.PHONY : assembler/main.cpp.o

assembler/main.i: assembler/main.cpp.i
.PHONY : assembler/main.i

# target to preprocess a source file
assembler/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/assembler_run.dir/build.make CMakeFiles/assembler_run.dir/assembler/main.cpp.i
.PHONY : assembler/main.cpp.i

assembler/main.s: assembler/main.cpp.s
.PHONY : assembler/main.s

# target to generate assembly for a file
assembler/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/assembler_run.dir/build.make CMakeFiles/assembler_run.dir/assembler/main.cpp.s
.PHONY : assembler/main.cpp.s

common/utils.o: common/utils.cpp.o
.PHONY : common/utils.o

# target to build an object file
common/utils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/assembler_run.dir/build.make CMakeFiles/assembler_run.dir/common/utils.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/disassembler_run.dir/build.make CMakeFiles/disassembler_run.dir/common/utils.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpu_run.dir/build.make CMakeFiles/cpu_run.dir/common/utils.cpp.o
.PHONY : common/utils.cpp.o

common/utils.i: common/utils.cpp.i
.PHONY : common/utils.i

# target to preprocess a source file
common/utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/assembler_run.dir/build.make CMakeFiles/assembler_run.dir/common/utils.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/disassembler_run.dir/build.make CMakeFiles/disassembler_run.dir/common/utils.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpu_run.dir/build.make CMakeFiles/cpu_run.dir/common/utils.cpp.i
.PHONY : common/utils.cpp.i

common/utils.s: common/utils.cpp.s
.PHONY : common/utils.s

# target to generate assembly for a file
common/utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/assembler_run.dir/build.make CMakeFiles/assembler_run.dir/common/utils.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/disassembler_run.dir/build.make CMakeFiles/disassembler_run.dir/common/utils.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpu_run.dir/build.make CMakeFiles/cpu_run.dir/common/utils.cpp.s
.PHONY : common/utils.cpp.s

cpu/cpu.o: cpu/cpu.cpp.o
.PHONY : cpu/cpu.o

# target to build an object file
cpu/cpu.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpu_run.dir/build.make CMakeFiles/cpu_run.dir/cpu/cpu.cpp.o
.PHONY : cpu/cpu.cpp.o

cpu/cpu.i: cpu/cpu.cpp.i
.PHONY : cpu/cpu.i

# target to preprocess a source file
cpu/cpu.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpu_run.dir/build.make CMakeFiles/cpu_run.dir/cpu/cpu.cpp.i
.PHONY : cpu/cpu.cpp.i

cpu/cpu.s: cpu/cpu.cpp.s
.PHONY : cpu/cpu.s

# target to generate assembly for a file
cpu/cpu.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpu_run.dir/build.make CMakeFiles/cpu_run.dir/cpu/cpu.cpp.s
.PHONY : cpu/cpu.cpp.s

cpu/main.o: cpu/main.cpp.o
.PHONY : cpu/main.o

# target to build an object file
cpu/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpu_run.dir/build.make CMakeFiles/cpu_run.dir/cpu/main.cpp.o
.PHONY : cpu/main.cpp.o

cpu/main.i: cpu/main.cpp.i
.PHONY : cpu/main.i

# target to preprocess a source file
cpu/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpu_run.dir/build.make CMakeFiles/cpu_run.dir/cpu/main.cpp.i
.PHONY : cpu/main.cpp.i

cpu/main.s: cpu/main.cpp.s
.PHONY : cpu/main.s

# target to generate assembly for a file
cpu/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpu_run.dir/build.make CMakeFiles/cpu_run.dir/cpu/main.cpp.s
.PHONY : cpu/main.cpp.s

disassembler/disassembler.o: disassembler/disassembler.cpp.o
.PHONY : disassembler/disassembler.o

# target to build an object file
disassembler/disassembler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/disassembler_run.dir/build.make CMakeFiles/disassembler_run.dir/disassembler/disassembler.cpp.o
.PHONY : disassembler/disassembler.cpp.o

disassembler/disassembler.i: disassembler/disassembler.cpp.i
.PHONY : disassembler/disassembler.i

# target to preprocess a source file
disassembler/disassembler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/disassembler_run.dir/build.make CMakeFiles/disassembler_run.dir/disassembler/disassembler.cpp.i
.PHONY : disassembler/disassembler.cpp.i

disassembler/disassembler.s: disassembler/disassembler.cpp.s
.PHONY : disassembler/disassembler.s

# target to generate assembly for a file
disassembler/disassembler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/disassembler_run.dir/build.make CMakeFiles/disassembler_run.dir/disassembler/disassembler.cpp.s
.PHONY : disassembler/disassembler.cpp.s

disassembler/main.o: disassembler/main.cpp.o
.PHONY : disassembler/main.o

# target to build an object file
disassembler/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/disassembler_run.dir/build.make CMakeFiles/disassembler_run.dir/disassembler/main.cpp.o
.PHONY : disassembler/main.cpp.o

disassembler/main.i: disassembler/main.cpp.i
.PHONY : disassembler/main.i

# target to preprocess a source file
disassembler/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/disassembler_run.dir/build.make CMakeFiles/disassembler_run.dir/disassembler/main.cpp.i
.PHONY : disassembler/main.cpp.i

disassembler/main.s: disassembler/main.cpp.s
.PHONY : disassembler/main.s

# target to generate assembly for a file
disassembler/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/disassembler_run.dir/build.make CMakeFiles/disassembler_run.dir/disassembler/main.cpp.s
.PHONY : disassembler/main.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.s
.PHONY : main.cpp.s

sfml_test.o: sfml_test.cpp.o
.PHONY : sfml_test.o

# target to build an object file
sfml_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sfml_test.dir/build.make CMakeFiles/sfml_test.dir/sfml_test.cpp.o
.PHONY : sfml_test.cpp.o

sfml_test.i: sfml_test.cpp.i
.PHONY : sfml_test.i

# target to preprocess a source file
sfml_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sfml_test.dir/build.make CMakeFiles/sfml_test.dir/sfml_test.cpp.i
.PHONY : sfml_test.cpp.i

sfml_test.s: sfml_test.cpp.s
.PHONY : sfml_test.s

# target to generate assembly for a file
sfml_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sfml_test.dir/build.make CMakeFiles/sfml_test.dir/sfml_test.cpp.s
.PHONY : sfml_test.cpp.s

stack/main.o: stack/main.cpp.o
.PHONY : stack/main.o

# target to build an object file
stack/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stack.dir/build.make CMakeFiles/stack.dir/stack/main.cpp.o
.PHONY : stack/main.cpp.o

stack/main.i: stack/main.cpp.i
.PHONY : stack/main.i

# target to preprocess a source file
stack/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stack.dir/build.make CMakeFiles/stack.dir/stack/main.cpp.i
.PHONY : stack/main.cpp.i

stack/main.s: stack/main.cpp.s
.PHONY : stack/main.s

# target to generate assembly for a file
stack/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stack.dir/build.make CMakeFiles/stack.dir/stack/main.cpp.s
.PHONY : stack/main.cpp.s

stack/stack.o: stack/stack.cpp.o
.PHONY : stack/stack.o

# target to build an object file
stack/stack.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stack.dir/build.make CMakeFiles/stack.dir/stack/stack.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/assembler_run.dir/build.make CMakeFiles/assembler_run.dir/stack/stack.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/disassembler_run.dir/build.make CMakeFiles/disassembler_run.dir/stack/stack.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpu_run.dir/build.make CMakeFiles/cpu_run.dir/stack/stack.cpp.o
.PHONY : stack/stack.cpp.o

stack/stack.i: stack/stack.cpp.i
.PHONY : stack/stack.i

# target to preprocess a source file
stack/stack.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stack.dir/build.make CMakeFiles/stack.dir/stack/stack.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/assembler_run.dir/build.make CMakeFiles/assembler_run.dir/stack/stack.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/disassembler_run.dir/build.make CMakeFiles/disassembler_run.dir/stack/stack.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpu_run.dir/build.make CMakeFiles/cpu_run.dir/stack/stack.cpp.i
.PHONY : stack/stack.cpp.i

stack/stack.s: stack/stack.cpp.s
.PHONY : stack/stack.s

# target to generate assembly for a file
stack/stack.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stack.dir/build.make CMakeFiles/stack.dir/stack/stack.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/assembler_run.dir/build.make CMakeFiles/assembler_run.dir/stack/stack.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/disassembler_run.dir/build.make CMakeFiles/disassembler_run.dir/stack/stack.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpu_run.dir/build.make CMakeFiles/cpu_run.dir/stack/stack.cpp.s
.PHONY : stack/stack.cpp.s

stack/stack_logs.o: stack/stack_logs.cpp.o
.PHONY : stack/stack_logs.o

# target to build an object file
stack/stack_logs.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stack.dir/build.make CMakeFiles/stack.dir/stack/stack_logs.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/assembler_run.dir/build.make CMakeFiles/assembler_run.dir/stack/stack_logs.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/disassembler_run.dir/build.make CMakeFiles/disassembler_run.dir/stack/stack_logs.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpu_run.dir/build.make CMakeFiles/cpu_run.dir/stack/stack_logs.cpp.o
.PHONY : stack/stack_logs.cpp.o

stack/stack_logs.i: stack/stack_logs.cpp.i
.PHONY : stack/stack_logs.i

# target to preprocess a source file
stack/stack_logs.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stack.dir/build.make CMakeFiles/stack.dir/stack/stack_logs.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/assembler_run.dir/build.make CMakeFiles/assembler_run.dir/stack/stack_logs.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/disassembler_run.dir/build.make CMakeFiles/disassembler_run.dir/stack/stack_logs.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpu_run.dir/build.make CMakeFiles/cpu_run.dir/stack/stack_logs.cpp.i
.PHONY : stack/stack_logs.cpp.i

stack/stack_logs.s: stack/stack_logs.cpp.s
.PHONY : stack/stack_logs.s

# target to generate assembly for a file
stack/stack_logs.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stack.dir/build.make CMakeFiles/stack.dir/stack/stack_logs.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/assembler_run.dir/build.make CMakeFiles/assembler_run.dir/stack/stack_logs.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/disassembler_run.dir/build.make CMakeFiles/disassembler_run.dir/stack/stack_logs.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpu_run.dir/build.make CMakeFiles/cpu_run.dir/stack/stack_logs.cpp.s
.PHONY : stack/stack_logs.cpp.s

stack/stack_verification.o: stack/stack_verification.cpp.o
.PHONY : stack/stack_verification.o

# target to build an object file
stack/stack_verification.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stack.dir/build.make CMakeFiles/stack.dir/stack/stack_verification.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/assembler_run.dir/build.make CMakeFiles/assembler_run.dir/stack/stack_verification.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/disassembler_run.dir/build.make CMakeFiles/disassembler_run.dir/stack/stack_verification.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpu_run.dir/build.make CMakeFiles/cpu_run.dir/stack/stack_verification.cpp.o
.PHONY : stack/stack_verification.cpp.o

stack/stack_verification.i: stack/stack_verification.cpp.i
.PHONY : stack/stack_verification.i

# target to preprocess a source file
stack/stack_verification.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stack.dir/build.make CMakeFiles/stack.dir/stack/stack_verification.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/assembler_run.dir/build.make CMakeFiles/assembler_run.dir/stack/stack_verification.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/disassembler_run.dir/build.make CMakeFiles/disassembler_run.dir/stack/stack_verification.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpu_run.dir/build.make CMakeFiles/cpu_run.dir/stack/stack_verification.cpp.i
.PHONY : stack/stack_verification.cpp.i

stack/stack_verification.s: stack/stack_verification.cpp.s
.PHONY : stack/stack_verification.s

# target to generate assembly for a file
stack/stack_verification.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stack.dir/build.make CMakeFiles/stack.dir/stack/stack_verification.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/assembler_run.dir/build.make CMakeFiles/assembler_run.dir/stack/stack_verification.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/disassembler_run.dir/build.make CMakeFiles/disassembler_run.dir/stack/stack_verification.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpu_run.dir/build.make CMakeFiles/cpu_run.dir/stack/stack_verification.cpp.s
.PHONY : stack/stack_verification.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... assembler_run"
	@echo "... cpu_run"
	@echo "... disassembler_run"
	@echo "... main"
	@echo "... sfml_test"
	@echo "... stack"
	@echo "... assembler/assembler.o"
	@echo "... assembler/assembler.i"
	@echo "... assembler/assembler.s"
	@echo "... assembler/main.o"
	@echo "... assembler/main.i"
	@echo "... assembler/main.s"
	@echo "... common/utils.o"
	@echo "... common/utils.i"
	@echo "... common/utils.s"
	@echo "... cpu/cpu.o"
	@echo "... cpu/cpu.i"
	@echo "... cpu/cpu.s"
	@echo "... cpu/main.o"
	@echo "... cpu/main.i"
	@echo "... cpu/main.s"
	@echo "... disassembler/disassembler.o"
	@echo "... disassembler/disassembler.i"
	@echo "... disassembler/disassembler.s"
	@echo "... disassembler/main.o"
	@echo "... disassembler/main.i"
	@echo "... disassembler/main.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... sfml_test.o"
	@echo "... sfml_test.i"
	@echo "... sfml_test.s"
	@echo "... stack/main.o"
	@echo "... stack/main.i"
	@echo "... stack/main.s"
	@echo "... stack/stack.o"
	@echo "... stack/stack.i"
	@echo "... stack/stack.s"
	@echo "... stack/stack_logs.o"
	@echo "... stack/stack_logs.i"
	@echo "... stack/stack_logs.s"
	@echo "... stack/stack_verification.o"
	@echo "... stack/stack_verification.i"
	@echo "... stack/stack_verification.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

